spring:
    application:
        name: part1-restful

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        #url: jdbc:mysql://localhost:3306/part1-restful?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        url: jdbc:mysql://localhost:3306/part1-restful?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: 1234

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    weather:
        api:
            service-key: "5454566156736b71373469564a4277"
