spring:
    application:
        name: part1-restful

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/part1-restful?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: 1234

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true


    api:
        weather:
            url: http://openapi.seoul.go.kr:8088
            key: 644f4a48416d696e35354f524d5a66
