spring:
    application:
        name: part1-restful

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/part1-restful?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: 1234

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect

    weather:
        api:
            service-key: 76587865496d696e39337154664545

    springdoc:
        api-docs:
            path: /api-docs
        swagger-ui:
            path: /swagger-ui.html
